version: "3"

services:
  app1db:
    image: postgres:12.2
    container_name: app1db
    restart: "always"
    ports:
      - 5432:5432
    env_file:
      - docker/.env
    volumes:
      - db_data:/var/lib/postgresql/data
  app1:
    build: .
    container_name: app1
    depends_on:
      - app1db
    restart: "always"
    ports:
      - 8080:8080
    environment:
      - DATABASE_DB=app1db:5432/phdb

volumes:
  db_data:
