version: "3"

services:
  postgres:
    image: postgres:12.2
    container_name: db
    restart: "always"
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
